spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calebe_dev
    username: calebe_dev_user
    password: calebe
  jpa:
    hibernate:
      ddl-auto: create-and
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    show-sql: true